[build]
  base    = "/"
  publish = "Betty"  # Replace "public" with your actual publish directory if different
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"
